<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Data"
    nsURI="http:///Data.ecore" nsPrefix="Data">
  <eSubpackages name="Kobra2" nsURI="http:///Data/Kobra2.ecore" nsPrefix="Data.Kobra2">
    <eSubpackages name="SUM" nsURI="http:///Data/Kobra2/SUM.ecore" nsPrefix="Data.Kobra2.SUM">
      <eSubpackages name="Structure" nsURI="http:///Data/Kobra2/SUM/Structure.ecore"
          nsPrefix="Data.Kobra2.SUM.Structure">
        <eSubpackages name="Types" nsURI="http:///Data/Kobra2/SUM/Structure/Types.ecore"
            nsPrefix="Data.Kobra2.SUM.Structure.Types">
          <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true"
              eSuperTypes="#//Kobra2/SUM/Structure/Types/DataType UML.ecore#//Classes/Kernel/PrimitiveType"/>
          <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="UML.ecore#//Classes/Kernel/DataType"/>
          <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//Kobra2/SUM/Structure/Types/DataType">
            <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiteral" ordered="false"
                unique="false" eType="#//Kobra2/SUM/Structure/Types/EnumerationLiteral"
                containment="true"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral"/>
          <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Kobra2/SUM/Structure/Types/PrimitiveType"/>
          <eClassifiers xsi:type="ecore:EClass" name="Numeric" eSuperTypes="#//Kobra2/SUM/Structure/Types/PrimitiveType"/>
          <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Kobra2/SUM/Structure/Types/PrimitiveType"/>
          <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//Kobra2/SUM/Structure/Types/Numeric"/>
          <eClassifiers xsi:type="ecore:EClass" name="UnllimitedNatural" eSuperTypes="#//Kobra2/SUM/Structure/Types/Numeric"/>
          <eClassifiers xsi:type="ecore:EClass" name="Real" eSuperTypes="#//Kobra2/SUM/Structure/Types/Numeric"/>
          <eClassifiers xsi:type="ecore:EClass" name="MessageType"/>
        </eSubpackages>
        <eSubpackages name="Elements" nsURI="http:///Data/Kobra2/SUM/Structure/Elements.ecore"
            nsPrefix="Data.Kobra2.SUM.Structure.Elements">
          <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
          <eClassifiers xsi:type="ecore:EClass" name="StructuralElement" abstract="true"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/Element"/>
          <eClassifiers xsi:type="ecore:EClass" name="StructuralBehavioralElement"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/Element"/>
          <eClassifiers xsi:type="ecore:EClass" name="BehavioralElement" abstract="true"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/Element"/>
          <eClassifiers xsi:type="ecore:EClass" name="TypeElement" abstract="true"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/StructuralElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="InstanceElement" abstract="true"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/StructuralElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//Kobra2/SUM/Structure/Elements/StructuralBehavioralElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Kobra2/SUM/Structure/Elements/StructuralBehavioralElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="Operation"/>
          <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Kobra2/SUM/Structure/Elements/StructuralBehavioralElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="QueryOperation" eSuperTypes="#//Kobra2/SUM/Structure/Elements/Operation"/>
          <eClassifiers xsi:type="ecore:EClass" name="EffectOperation" eSuperTypes="#//Kobra2/SUM/Structure/Elements/Operation"/>
          <eClassifiers xsi:type="ecore:EClass" name="ConstraintElement" eSuperTypes="#//Kobra2/SUM/Structure/Elements/Element"/>
          <eClassifiers xsi:type="ecore:EClass" name="CommonConstraintElement" eSuperTypes="#//Kobra2/SUM/Structure/Elements/ConstraintElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="BehavioralConstraintElement"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/ConstraintElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="StructuralConstraintElement"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/ConstraintElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="ActiviityElement" abstract="true"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/BehavioralElement"/>
          <eClassifiers xsi:type="ecore:EClass" name="ProtocolElement" abstract="true"
              eSuperTypes="#//Kobra2/SUM/Structure/Elements/BehavioralElement"/>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
